#!/usr/bin/env node
// Copies the compiled Compact zk assets (prover keys, verifier keys, zkir)
// AND the contract JS into frontend directories so the browser can use them.
// Generated by `npm run compile` at the repo root (contracts/managed/…).
import { mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..', '..'); // repo root
const src = join(root, 'contracts', 'managed', 'supply-chain');
const dest = join(__dirname, '..', 'public', 'managed', 'supply-chain');
const contractDest = join(__dirname, '..', 'contracts', 'supply-chain', 'contract');

if (!existsSync(join(src, 'contract', 'index.js'))) {
  console.error(
    '  ⚠ Compiled contract not found at contracts/managed/supply-chain.\n' +
    '    Run `npm run compile` at the repo root first.',
  );
  process.exit(1);
}

// Copy the contract JS + types to frontend/contracts/supply-chain/contract/
// This ensures the contract uses the SAME compact-runtime instance as the
// rest of the frontend (fixes cross-package ChargedState instanceof errors).
mkdirSync(contractDest, { recursive: true });
copyFileSync(join(src, 'contract', 'index.js'), join(contractDest, 'index.js'));
if (existsSync(join(src, 'contract', 'index.d.ts'))) {
  copyFileSync(join(src, 'contract', 'index.d.ts'), join(contractDest, 'index.d.ts'));
}
if (existsSync(join(src, 'contract', 'index.js.map'))) {
  copyFileSync(join(src, 'contract', 'index.js.map'), join(contractDest, 'index.js.map'));
}
console.log(`  ✓ Copied contract index.js + types to frontend/contracts/supply-chain/contract/`);

const SUBDIRS = ['keys', 'zkir'];

rmSync(dest, { recursive: true, force: true });
for (const sub of SUBDIRS) {
  const fromDir = join(src, sub);
  const toDir = join(dest, sub);
  if (!existsSync(fromDir)) continue;
  mkdirSync(toDir, { recursive: true });
  for (const file of ['registerProduct', 'recordCheckpoint', 'verifyAuthenticity']) {
    for (const ext of sub === 'keys' ? ['.prover', '.verifier'] : ['.bzkir']) {
      const f = join(fromDir, `${file}${ext}`);
      if (existsSync(f)) copyFileSync(f, join(toDir, `${file}${ext}`));
    }
  }
}
console.log(`  ✓ Copied zk assets to frontend/public/managed/supply-chain/`);
