#!/usr/bin/env node
// Copies the compiled Compact zk assets (prover keys, verifier keys, zkir)
// into frontend/public/managed/ so the browser can fetch them over HTTP.
// Generated by `npm run compile` at the repo root (contracts/managed/…).
import { mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..', '..'); // repo root
const src = join(root, 'contracts', 'managed', 'supply-chain');
const dest = join(__dirname, '..', 'public', 'managed', 'supply-chain');

const SUBDIRS = ['keys', 'zkir'];

if (!existsSync(join(src, 'contract', 'index.js'))) {
  console.error(
    '  ⚠ Compiled contract not found at contracts/managed/supply-chain.\n' +
    '    Run `npm run compile` at the repo root first.',
  );
  process.exit(1);
}

rmSync(dest, { recursive: true, force: true });
for (const sub of SUBDIRS) {
  const fromDir = join(src, sub);
  const toDir = join(dest, sub);
  if (!existsSync(fromDir)) continue;
  mkdirSync(toDir, { recursive: true });
  for (const file of ['registerProduct', 'recordCheckpoint', 'verifyAuthenticity']) {
    for (const ext of sub === 'keys' ? ['.prover', '.verifier'] : ['.bzkir']) {
      const f = join(fromDir, `${file}${ext}`);
      if (existsSync(f)) copyFileSync(f, join(toDir, `${file}${ext}`));
    }
  }
}
console.log(`  ✓ Copied zk assets to frontend/public/managed/supply-chain/`);
